Controllers/SongController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MusicWorld.Data;
using MusicWorld.Models;
using MusicWorld.Service.Interfaces;
using System.Threading.Tasks;

namespace MusicWorld.Controllers
{
    public class SongController : Controller
    {
        private readonly IMapper mapper;
        private readonly MusicContext _context;
        private readonly ISongService songService;

        public SongController(IMapper mapper, MusicContext context, ISongService songService)
        {
            this.mapper = mapper;
            this._context = context;
            this.songService = songService;
        }
        [HttpGet]
        public async Task<IActionResult> CreateSong(string albumName)
        {
            TempData["Album name"] = albumName;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateSong(SongViewModel model)
        {
            await songService.CreateSong(model, TempData["Album name"].ToString());
            return RedirectToAction("AllArtists", "Artist");
        }
        public async Task<IActionResult> DeleteSong(string songName)
        {
            await songService.DeleteSong(songName);
            return RedirectToAction("AllArtists", "Artist");
        }
        [HttpGet]
        public async Task<IActionResult> EditSong(string songName)
        {
            TempData["Song Name"] = songName;

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> EditSong(SongViewModel model)
        {
            await songService.EditSong(model, TempData["Song Name"].ToString());
            TempData.Clear();
            return RedirectToAction("AllArtists", "Artist");
        }
        public async Task<IActionResult> AllSongs()
        {
            return View(await songService.GetAllSongs());
        }
        public async Task<IActionResult> DetailsSong(string songName)
        {
            return View(mapper.Map<SongViewModel>(await songService.GetSongByName(songName)));
        }


    }
}

Views/Song/CreateSong.cshtml
@model MusicWorld.Models.SongViewModel

@{
    ViewData["Title"] = "Create a album";
}
<h1 class="mainColor">Add a Song</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Song" asp-action="CreateSong" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Name</label>
                <input asp-for="Name" class="titleInput" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label">Duration</label>
                <input asp-for="Duration" class="date" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Views/Song/DetailsSong.cshtml
@model MusicWorld.Models.SongViewModel

<h1>@Model.Name</h1>
<p></p>

<div>
    <h5><b>Details:</b></h5>
    <p>Created by: @Model.Artist.Name</p>
    <p>From album: @Model.Album.Name</p>
    <p>Duration: @Model.Duration</p>
</div>

Views/Song/EditSong.cshtml
@model MusicWorld.Models.SongViewModel
<h1>Edit Song</h1>

<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="EditSong">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="AllArtists">Back to List</a>
</div>